import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:go_router/go_router.dart';

/// Donor "Transparency Mode" — Automated impact narratives generated by the AI Brain.
class TransparencyDashboard extends StatefulWidget {
  const TransparencyDashboard({super.key});

  @override
  State<TransparencyDashboard> createState() => _TransparencyDashboardState();
}

class _TransparencyDashboardState extends State<TransparencyDashboard> {
  bool _isLoading = true;

  final _impactStats = {
    'reports_resolved': 184,
    'volunteers_active': 67,
    'wards_covered': 12,
    'people_impacted': 23400,
  };

  final _impactStories = [
    _ImpactStory(
      title: 'Clean Water Restored in Ward 23',
      narrative:
          'Following 14 citizen reports over 3 weeks, a broken pipeline in Gomti Nagar was identified and repaired. '
          'The AI urgency engine escalated this issue to critical after correlating water contamination reports '
          'with health clinic data from the same ward. 1,200 residents now have clean water access.',
      category: 'Water',
      resolvedDate: '2025-04-18',
      impactCount: 1200,
    ),
    _ImpactStory(
      title: 'Road Safety — Chinhat Crossing Fixed',
      narrative:
          'Multiple photo reports of a dangerous pothole at Chinhat crossing triggered automatic volunteer matching. '
          '3 volunteers coordinated with Nagar Nigam to install temporary barriers within 24 hours, followed by '
          'permanent repair within a week. Zero accidents reported since intervention.',
      category: 'Road',
      resolvedDate: '2025-04-10',
      impactCount: 3500,
    ),
    _ImpactStory(
      title: 'Sanitation Drive — Block C Colony',
      narrative:
          'Community-reported garbage accumulation was flagged by the system as a disease vector risk. '
          'Matched 8 volunteers and coordinated a weekend cleanup drive. Post-cleanup, health reports '
          'from the area showed a 40% reduction in gastric complaints.',
      category: 'Sanitation',
      resolvedDate: '2025-04-05',
      impactCount: 800,
    ),
  ];

  @override
  void initState() {
    super.initState();
    Future.delayed(const Duration(milliseconds: 600), () {
      if (mounted) setState(() => _isLoading = false);
    });
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Transparency Mode'),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () async {
              await FirebaseAuth.instance.signOut();
              if (!context.mounted) return;
              context.go('/login');
            },
          ),
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Impact Overview',
                      style: theme.textTheme.titleLarge
                          ?.copyWith(fontWeight: FontWeight.w600)),
                  const SizedBox(height: 16),

                  // Stats grid
                  GridView.count(
                    crossAxisCount: 2,
                    shrinkWrap: true,
                    physics: const NeverScrollableScrollPhysics(),
                    mainAxisSpacing: 12,
                    crossAxisSpacing: 12,
                    childAspectRatio: 1.6,
                    children: [
                      _ImpactCard(
                        label: 'Issues Resolved',
                        value: '${_impactStats['reports_resolved']}',
                        icon: Icons.check_circle_rounded,
                        color: Colors.green,
                      ),
                      _ImpactCard(
                        label: 'Active Volunteers',
                        value: '${_impactStats['volunteers_active']}',
                        icon: Icons.people_rounded,
                        color: Colors.blue,
                      ),
                      _ImpactCard(
                        label: 'Wards Covered',
                        value: '${_impactStats['wards_covered']}',
                        icon: Icons.map_rounded,
                        color: Colors.orange,
                      ),
                      _ImpactCard(
                        label: 'People Impacted',
                        value: '23.4K',
                        icon: Icons.favorite_rounded,
                        color: Colors.red,
                      ),
                    ],
                  ),

                  const SizedBox(height: 32),
                  Row(
                    children: [
                      Text('Impact Stories',
                          style: theme.textTheme.titleLarge
                              ?.copyWith(fontWeight: FontWeight.w600)),
                      const SizedBox(width: 8),
                      Chip(
                        label: Text('AI Generated',
                            style: TextStyle(
                                fontSize: 10,
                                color: theme.colorScheme.primary)),
                        backgroundColor: theme.colorScheme.primaryContainer
                            .withValues(alpha: 0.5),
                        side: BorderSide.none,
                        padding: EdgeInsets.zero,
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),

                  // Impact story cards
                  ...List.generate(_impactStories.length, (index) {
                    final story = _impactStories[index];
                    return Card(
                      margin: const EdgeInsets.only(bottom: 16),
                      child: Padding(
                        padding: const EdgeInsets.all(20),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Chip(label: Text(story.category)),
                                const Spacer(),
                                Text(story.resolvedDate,
                                    style: theme.textTheme.labelSmall?.copyWith(
                                        color: theme
                                            .colorScheme.onSurfaceVariant)),
                              ],
                            ),
                            const SizedBox(height: 12),
                            Text(story.title,
                                style: theme.textTheme.titleMedium
                                    ?.copyWith(fontWeight: FontWeight.w600)),
                            const SizedBox(height: 8),
                            Text(story.narrative,
                                style: theme.textTheme.bodyMedium?.copyWith(
                                  color: theme.colorScheme.onSurfaceVariant,
                                  height: 1.5,
                                )),
                            const SizedBox(height: 12),
                            Row(
                              children: [
                                Icon(Icons.people,
                                    size: 16, color: theme.colorScheme.primary),
                                const SizedBox(width: 4),
                                Text('${story.impactCount} people impacted',
                                    style:
                                        theme.textTheme.labelMedium?.copyWith(
                                      color: theme.colorScheme.primary,
                                      fontWeight: FontWeight.w600,
                                    )),
                              ],
                            ),
                          ],
                        ),
                      ),
                    );
                  }),
                ],
              ),
            ),
    );
  }
}

class _ImpactStory {
  final String title;
  final String narrative;
  final String category;
  final String resolvedDate;
  final int impactCount;

  const _ImpactStory({
    required this.title,
    required this.narrative,
    required this.category,
    required this.resolvedDate,
    required this.impactCount,
  });
}

class _ImpactCard extends StatelessWidget {
  final String label;
  final String value;
  final IconData icon;
  final Color color;

  const _ImpactCard({
    required this.label,
    required this.value,
    required this.icon,
    required this.color,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon, color: color, size: 24),
            const SizedBox(height: 8),
            Text(value,
                style: Theme.of(context)
                    .textTheme
                    .headlineSmall
                    ?.copyWith(fontWeight: FontWeight.bold)),
            Text(label,
                style: Theme.of(context).textTheme.labelSmall?.copyWith(
                    color: Theme.of(context).colorScheme.onSurfaceVariant)),
          ],
        ),
      ),
    );
  }
}
